INFO:root:67267200
INFO:root:No: 1	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010720968246459961, error_no=2, timestamp=1528958543.426724)	[('tile_y', [16, 2, 7, 112]), ('tile_x', [4, 1, 1, 8]), ('tile_r', [4, 2, 512]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,43839083
INFO:root:No: 2	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01109004020690918, error_no=2, timestamp=1528958543.448827)	[('tile_y', [2, 1, 448, 28]), ('tile_x', [1, 32, 1, 1]), ('tile_r', [4, 256, 4]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,15289315
INFO:root:No: 3	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958553.50445)	[('tile_y', [448, 28, 1, 2]), ('tile_x', [2, 2, 2, 4]), ('tile_r', [128, 1, 32]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,6866537
INFO:root:No: 4	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011363029479980469, error_no=2, timestamp=1528958553.520409)	[('tile_y', [56, 4, 2, 56]), ('tile_x', [1, 4, 4, 2]), ('tile_r', [32, 128, 1]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,34568079
INFO:root:No: 5	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01145315170288086, error_no=2, timestamp=1528958553.541388)	[('tile_y', [448, 8, 7, 1]), ('tile_x', [4, 2, 2, 2]), ('tile_r', [4, 256, 4]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,37758685
INFO:root:No: 6	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011031866073608398, error_no=2, timestamp=1528958553.561843)	[('tile_y', [8, 784, 2, 2]), ('tile_x', [2, 4, 2, 2]), ('tile_r', [4, 128, 8]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,16570776
INFO:root:No: 7	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958563.615652)	[('tile_y', [224, 2, 1, 56]), ('tile_x', [4, 4, 2, 1]), ('tile_r', [64, 16, 4]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,37225664
INFO:root:No: 8	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01105499267578125, error_no=2, timestamp=1528958563.631433)	[('tile_y', [1, 98, 128, 2]), ('tile_x', [2, 8, 1, 2]), ('tile_r', [64, 1, 64]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,41448548
INFO:root:No: 9	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.019646167755126953, error_no=2, timestamp=1528958563.660788)	[('tile_y', [4, 64, 49, 2]), ('tile_x', [1, 4, 2, 4]), ('tile_r', [32, 32, 4]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,48633701
INFO:root:No: 10	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01134181022644043, error_no=2, timestamp=1528958563.689411)	[('tile_y', [16, 28, 14, 4]), ('tile_x', [2, 8, 1, 2]), ('tile_r', [4, 1, 1024]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,21736701
INFO:root:No: 11	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010618925094604492, error_no=2, timestamp=1528958563.709493)	[('tile_y', [16, 49, 8, 4]), ('tile_x', [1, 2, 16, 1]), ('tile_r', [1, 512, 8]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,5586487
INFO:root:No: 12	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.015462160110473633, error_no=2, timestamp=1528958563.735032)	[('tile_y', [64, 7, 4, 14]), ('tile_x', [1, 1, 1, 32]), ('tile_r', [128, 8, 4]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,48416586
INFO:root:No: 13	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010921955108642578, error_no=2, timestamp=1528958563.76769)	[('tile_y', [49, 8, 8, 8]), ('tile_x', [1, 1, 16, 2]), ('tile_r', [32, 64, 2]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,24841253
INFO:root:No: 14	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011034965515136719, error_no=2, timestamp=1528958563.78865)	[('tile_y', [56, 14, 1, 32]), ('tile_x', [4, 1, 2, 4]), ('tile_r', [16, 2, 128]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,31259123
INFO:root:No: 15	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.16539812088012695, error_no=2, timestamp=1528958563.96391)	[('tile_y', [128, 14, 7, 2]), ('tile_x', [1, 8, 1, 4]), ('tile_r', [16, 1, 256]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,65505407
INFO:root:No: 16	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010487794876098633, error_no=2, timestamp=1528958564.028494)	[('tile_y', [16, 224, 1, 7]), ('tile_x', [2, 2, 8, 1]), ('tile_r', [2, 128, 16]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,6565629
INFO:root:No: 17	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01022481918334961, error_no=2, timestamp=1528958564.049095)	[('tile_y', [1, 1568, 4, 4]), ('tile_x', [2, 1, 1, 16]), ('tile_r', [4096, 1, 1]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,44959862
INFO:root:No: 18	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.0109710693359375, error_no=2, timestamp=1528958564.070794)	[('tile_y', [8, 8, 196, 2]), ('tile_x', [1, 16, 2, 1]), ('tile_r', [32, 8, 16]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,39692952
INFO:root:No: 19	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010795116424560547, error_no=2, timestamp=1528958564.091514)	[('tile_y', [8, 64, 1, 49]), ('tile_x', [8, 1, 4, 1]), ('tile_r', [8, 8, 64]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,30579414
INFO:root:No: 20	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.0190122127532959, error_no=2, timestamp=1528958564.124658)	[('tile_y', [7, 4, 56, 16]), ('tile_x', [4, 2, 4, 1]), ('tile_r', [32, 2, 64]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,63968585
INFO:root:No: 21	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.015141963958740234, error_no=2, timestamp=1528958564.160294)	[('tile_y', [4, 32, 2, 98]), ('tile_x', [2, 8, 1, 2]), ('tile_r', [32, 8, 16]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,28513821
INFO:root:No: 22	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.025802135467529297, error_no=2, timestamp=1528958564.217472)	[('tile_y', [1, 8, 224, 14]), ('tile_x', [4, 1, 1, 8]), ('tile_r', [2, 512, 4]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,37924875
INFO:root:No: 23	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011518001556396484, error_no=2, timestamp=1528958564.240557)	[('tile_y', [64, 98, 2, 2]), ('tile_x', [1, 1, 4, 8]), ('tile_r', [2, 256, 8]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,16744569
INFO:root:No: 24	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011649131774902344, error_no=2, timestamp=1528958564.261768)	[('tile_y', [64, 7, 14, 4]), ('tile_x', [4, 1, 2, 4]), ('tile_r', [2, 256, 8]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,27931897
INFO:root:No: 25	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958574.318909)	[('tile_y', [224, 7, 8, 2]), ('tile_x', [2, 8, 2, 1]), ('tile_r', [128, 4, 8]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,49546623
INFO:root:No: 26	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01803898811340332, error_no=2, timestamp=1528958574.341724)	[('tile_y', [1, 64, 14, 28]), ('tile_x', [4, 2, 4, 1]), ('tile_r', [4, 1, 1024]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,66555876
INFO:root:No: 27	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01176905632019043, error_no=2, timestamp=1528958574.372498)	[('tile_y', [56, 2, 28, 8]), ('tile_x', [1, 8, 2, 2]), ('tile_r', [4, 32, 32]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,18668083
INFO:root:No: 28	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010638952255249023, error_no=2, timestamp=1528958574.392235)	[('tile_y', [28, 224, 4, 1]), ('tile_x', [1, 2, 8, 2]), ('tile_r', [2, 16, 128]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,31614073
INFO:root:No: 29	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011108160018920898, error_no=2, timestamp=1528958574.413556)	[('tile_y', [2, 4, 196, 16]), ('tile_x', [8, 2, 1, 2]), ('tile_r', [4, 2, 512]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,43785800
INFO:root:No: 30	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010917901992797852, error_no=2, timestamp=1528958574.434124)	[('tile_y', [128, 4, 1, 49]), ('tile_x', [1, 1, 4, 8]), ('tile_r', [1, 4096, 1]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,46437010
INFO:root:No: 31	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010653972625732422, error_no=2, timestamp=1528958574.454666)	[('tile_y', [256, 2, 1, 49]), ('tile_x', [2, 1, 8, 2]), ('tile_r', [32, 32, 4]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,14981409
INFO:root:No: 32	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958584.514066)	[('tile_y', [56, 2, 1, 224]), ('tile_x', [2, 1, 8, 2]), ('tile_r', [256, 4, 4]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,59456988
INFO:root:No: 33	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.04537701606750488, error_no=2, timestamp=1528958584.565525)	[('tile_y', [64, 49, 2, 4]), ('tile_x', [1, 8, 4, 1]), ('tile_r', [8, 512, 1]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,45985033
INFO:root:No: 34	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011446952819824219, error_no=2, timestamp=1528958584.601085)	[('tile_y', [448, 1, 4, 14]), ('tile_x', [4, 4, 2, 1]), ('tile_r', [2, 64, 32]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,41167583
INFO:root:No: 35	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.024454832077026367, error_no=2, timestamp=1528958584.635964)	[('tile_y', [32, 1, 196, 4]), ('tile_x', [1, 1, 8, 4]), ('tile_r', [32, 2, 64]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,64040583
INFO:root:No: 36	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.012042045593261719, error_no=2, timestamp=1528958584.661441)	[('tile_y', [2, 1, 49, 256]), ('tile_x', [1, 16, 1, 2]), ('tile_r', [128, 8, 4]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,25929047
INFO:root:No: 37	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.10750818252563477, error_no=2, timestamp=1528958584.777882)	[('tile_y', [112, 2, 1, 112]), ('tile_x', [4, 2, 1, 4]), ('tile_r', [2, 16, 128]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,65256053
INFO:root:No: 38	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011198997497558594, error_no=2, timestamp=1528958584.801086)	[('tile_y', [2, 49, 32, 8]), ('tile_x', [1, 1, 32, 1]), ('tile_r', [2048, 1, 2]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,12857896
INFO:root:No: 39	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011245012283325195, error_no=2, timestamp=1528958584.822573)	[('tile_y', [4, 98, 1, 64]), ('tile_x', [2, 4, 4, 1]), ('tile_r', [1024, 2, 2]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,24177556
INFO:root:No: 40	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958594.87752)	[('tile_y', [1792, 1, 14, 1]), ('tile_x', [8, 2, 2, 1]), ('tile_r', [16, 8, 32]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,7161122
INFO:root:No: 41	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.012457847595214844, error_no=2, timestamp=1528958594.894811)	[('tile_y', [14, 4, 224, 2]), ('tile_x', [4, 4, 2, 1]), ('tile_r', [8, 8, 64]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,19360558
INFO:root:No: 42	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.016843080520629883, error_no=2, timestamp=1528958594.941358)	[('tile_y', [224, 4, 4, 7]), ('tile_x', [2, 2, 4, 2]), ('tile_r', [4, 32, 32]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,29883456
INFO:root:No: 43	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01556086540222168, error_no=2, timestamp=1528958594.979728)	[('tile_y', [2, 1, 49, 256]), ('tile_x', [1, 1, 2, 16]), ('tile_r', [2, 128, 16]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,51495247
INFO:root:No: 44	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.041790008544921875, error_no=2, timestamp=1528958595.055179)	[('tile_y', [32, 2, 4, 98]), ('tile_x', [2, 4, 2, 2]), ('tile_r', [2, 8, 256]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,54641025
INFO:root:No: 45	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01331186294555664, error_no=2, timestamp=1528958595.095265)	[('tile_y', [7, 8, 4, 112]), ('tile_x', [1, 2, 4, 4]), ('tile_r', [32, 128, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,57017078
INFO:root:No: 46	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.025770187377929688, error_no=2, timestamp=1528958595.146294)	[('tile_y', [4, 7, 112, 8]), ('tile_x', [1, 1, 8, 4]), ('tile_r', [128, 2, 16]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,50735325
INFO:root:No: 47	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011113882064819336, error_no=2, timestamp=1528958595.168799)	[('tile_y', [49, 4, 2, 64]), ('tile_x', [2, 16, 1, 1]), ('tile_r', [4, 512, 2]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,36354561
INFO:root:No: 48	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.11314916610717773, error_no=2, timestamp=1528958595.292545)	[('tile_y', [1, 196, 4, 32]), ('tile_x', [2, 8, 2, 1]), ('tile_r', [32, 2, 64]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,52750953
INFO:root:No: 49	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.04319286346435547, error_no=2, timestamp=1528958595.395773)	[('tile_y', [2, 49, 16, 16]), ('tile_x', [4, 4, 1, 2]), ('tile_r', [2048, 2, 1]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,45019964
INFO:root:No: 50	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.013383865356445312, error_no=2, timestamp=1528958595.435555)	[('tile_y', [14, 1, 128, 14]), ('tile_x', [16, 1, 1, 2]), ('tile_r', [8, 128, 4]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,15201068
INFO:root:No: 51	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.019433021545410156, error_no=2, timestamp=1528958595.48155)	[('tile_y', [16, 49, 16, 2]), ('tile_x', [4, 1, 1, 8]), ('tile_r', [1, 4, 1024]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,10820062
INFO:root:No: 52	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.061341047286987305, error_no=2, timestamp=1528958595.564824)	[('tile_y', [2, 4, 7, 448]), ('tile_x', [1, 4, 2, 4]), ('tile_r', [4, 4, 256]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,65760098
INFO:root:No: 53	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.02379298210144043, error_no=2, timestamp=1528958595.649174)	[('tile_y', [8, 784, 1, 4]), ('tile_x', [2, 4, 1, 4]), ('tile_r', [4, 1024, 1]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,1316219
INFO:root:No: 54	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.024000167846679688, error_no=2, timestamp=1528958595.694276)	[('tile_y', [784, 32, 1, 1]), ('tile_x', [1, 8, 2, 2]), ('tile_r', [4, 512, 2]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,2774208
INFO:root:No: 55	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.03043985366821289, error_no=2, timestamp=1528958595.738874)	[('tile_y', [7, 128, 2, 14]), ('tile_x', [16, 2, 1, 1]), ('tile_r', [1, 4, 1024]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,55566579
INFO:root:No: 56	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.02650594711303711, error_no=2, timestamp=1528958595.8086)	[('tile_y', [14, 64, 14, 2]), ('tile_x', [16, 2, 1, 1]), ('tile_r', [2, 16, 128]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,20330648
INFO:root:No: 57	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.031466007232666016, error_no=2, timestamp=1528958595.892933)	[('tile_y', [1, 2, 896, 14]), ('tile_x', [2, 1, 4, 4]), ('tile_r', [8, 1, 512]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,10075082
INFO:root:No: 58	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958605.984646)	[('tile_y', [28, 128, 1, 7]), ('tile_x', [8, 1, 4, 1]), ('tile_r', [512, 2, 4]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,3228228
INFO:root:No: 59	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01060795783996582, error_no=2, timestamp=1528958606.000666)	[('tile_y', [4, 64, 49, 2]), ('tile_x', [2, 1, 2, 8]), ('tile_r', [32, 4, 32]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,29553101
INFO:root:No: 60	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010215997695922852, error_no=2, timestamp=1528958606.022122)	[('tile_y', [4, 6272, 1, 1]), ('tile_x', [1, 1, 1, 32]), ('tile_r', [1024, 1, 4]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,3201027
INFO:root:No: 61	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.016340970993041992, error_no=2, timestamp=1528958606.049884)	[('tile_y', [28, 28, 2, 16]), ('tile_x', [1, 4, 4, 2]), ('tile_r', [4, 1, 1024]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,66599709
INFO:root:No: 62	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010819196701049805, error_no=2, timestamp=1528958606.081715)	[('tile_y', [2, 98, 128, 1]), ('tile_x', [1, 8, 2, 2]), ('tile_r', [1, 1, 4096]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,33574453
INFO:root:No: 63	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011096000671386719, error_no=2, timestamp=1528958606.102851)	[('tile_y', [2, 7, 896, 2]), ('tile_x', [2, 1, 2, 8]), ('tile_r', [4, 4, 256]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,32140386
INFO:root:No: 64	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.012701034545898438, error_no=2, timestamp=1528958606.125442)	[('tile_y', [112, 16, 1, 14]), ('tile_x', [2, 1, 2, 8]), ('tile_r', [1, 2048, 2]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,59121755
INFO:root:No: 65	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.18562602996826172, error_no=2, timestamp=1528958606.335356)	[('tile_y', [32, 392, 2, 1]), ('tile_x', [2, 4, 1, 4]), ('tile_r', [256, 2, 8]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,49486848
INFO:root:No: 66	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.14075589179992676, error_no=2, timestamp=1528958606.510036)	[('tile_y', [2, 14, 1, 896]), ('tile_x', [2, 4, 2, 2]), ('tile_r', [2, 16, 128]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,65236539
INFO:root:No: 67	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010605812072753906, error_no=2, timestamp=1528958606.549471)	[('tile_y', [1, 1568, 16, 1]), ('tile_x', [4, 1, 2, 4]), ('tile_r', [128, 32, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,23126557
INFO:root:No: 68	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958616.6043)	[('tile_y', [56, 2, 8, 28]), ('tile_x', [2, 4, 4, 1]), ('tile_r', [1024, 4, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,22698861
INFO:root:No: 69	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.012278079986572266, error_no=2, timestamp=1528958616.621324)	[('tile_y', [64, 14, 7, 4]), ('tile_x', [1, 2, 8, 2]), ('tile_r', [8, 32, 16]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,6358668
INFO:root:No: 70	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010983943939208984, error_no=2, timestamp=1528958616.657095)	[('tile_y', [7, 112, 2, 16]), ('tile_x', [2, 4, 4, 1]), ('tile_r', [64, 2, 32]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,18140313
INFO:root:No: 71	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011389017105102539, error_no=2, timestamp=1528958616.678589)	[('tile_y', [8, 7, 56, 8]), ('tile_x', [4, 2, 4, 1]), ('tile_r', [1, 16, 256]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,9883508
INFO:root:No: 72	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011712074279785156, error_no=2, timestamp=1528958616.699757)	[('tile_y', [112, 7, 32, 1]), ('tile_x', [1, 4, 8, 1]), ('tile_r', [16, 64, 4]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,37490377
INFO:root:No: 73	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011403799057006836, error_no=2, timestamp=1528958616.720358)	[('tile_y', [2, 1, 2, 6272]), ('tile_x', [1, 16, 1, 2]), ('tile_r', [8, 256, 2]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,58700393
INFO:root:No: 74	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011559009552001953, error_no=2, timestamp=1528958616.741413)	[('tile_y', [1, 8, 4, 784]), ('tile_x', [4, 2, 2, 2]), ('tile_r', [16, 64, 4]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,37514328
INFO:root:No: 75	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010658025741577148, error_no=2, timestamp=1528958616.761442)	[('tile_y', [4, 1, 196, 32]), ('tile_x', [16, 2, 1, 1]), ('tile_r', [4, 128, 8]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,38935002
INFO:root:No: 76	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.034883975982666016, error_no=2, timestamp=1528958616.806419)	[('tile_y', [49, 2, 2, 128]), ('tile_x', [1, 1, 16, 2]), ('tile_r', [32, 8, 16]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,50960525
INFO:root:No: 77	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010629892349243164, error_no=2, timestamp=1528958616.851501)	[('tile_y', [1, 1, 8, 3136]), ('tile_x', [2, 16, 1, 1]), ('tile_r', [32, 128, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,56929386
INFO:root:No: 78	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010660886764526367, error_no=2, timestamp=1528958616.87228)	[('tile_y', [8, 1, 32, 98]), ('tile_x', [1, 16, 2, 1]), ('tile_r', [4, 256, 4]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,26511842
INFO:root:No: 79	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01875591278076172, error_no=2, timestamp=1528958616.904796)	[('tile_y', [2, 32, 14, 28]), ('tile_x', [8, 1, 2, 2]), ('tile_r', [8, 1, 512]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,54882675
INFO:root:No: 80	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.014672994613647461, error_no=2, timestamp=1528958616.940324)	[('tile_y', [1, 49, 8, 64]), ('tile_x', [4, 1, 8, 1]), ('tile_r', [2, 2, 1024]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,10629984
INFO:root:No: 81	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.033979177474975586, error_no=2, timestamp=1528958616.9999)	[('tile_y', [4, 8, 2, 392]), ('tile_x', [1, 2, 8, 2]), ('tile_r', [256, 1, 16]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,39377660
INFO:root:No: 82	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.012099981307983398, error_no=2, timestamp=1528958617.048342)	[('tile_y', [112, 2, 56, 2]), ('tile_x', [8, 1, 2, 2]), ('tile_r', [16, 16, 16]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,17428905
INFO:root:No: 83	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958627.118303)	[('tile_y', [32, 1, 112, 7]), ('tile_x', [1, 2, 2, 8]), ('tile_r', [4096, 1, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,22533348
INFO:root:No: 84	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.0526120662689209, error_no=2, timestamp=1528958627.175625)	[('tile_y', [14, 112, 2, 8]), ('tile_x', [2, 2, 4, 2]), ('tile_r', [16, 1, 256]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,54277214
INFO:root:No: 85	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011070013046264648, error_no=2, timestamp=1528958627.203264)	[('tile_y', [64, 8, 7, 7]), ('tile_x', [1, 1, 8, 4]), ('tile_r', [1, 256, 16]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,29175073
INFO:root:No: 86	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01139688491821289, error_no=2, timestamp=1528958627.224351)	[('tile_y', [16, 7, 1, 224]), ('tile_x', [2, 2, 4, 2]), ('tile_r', [4, 16, 64]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,41958190
INFO:root:No: 87	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.1844179630279541, error_no=2, timestamp=1528958627.418172)	[('tile_y', [1, 392, 1, 64]), ('tile_x', [8, 4, 1, 1]), ('tile_r', [4, 4, 256]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,54460558
INFO:root:No: 88	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958637.50064)	[('tile_y', [56, 28, 16, 1]), ('tile_x', [2, 1, 2, 8]), ('tile_r', [2048, 2, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,22653547
INFO:root:No: 89	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01371908187866211, error_no=2, timestamp=1528958637.519334)	[('tile_y', [28, 16, 8, 7]), ('tile_x', [1, 8, 4, 1]), ('tile_r', [4, 64, 16]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,51282886
INFO:root:No: 90	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.11382412910461426, error_no=2, timestamp=1528958637.656795)	[('tile_y', [4, 14, 1, 448]), ('tile_x', [1, 2, 1, 16]), ('tile_r', [64, 2, 32]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,63073883
INFO:root:No: 91	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958647.757594)	[('tile_y', [256, 1, 7, 14]), ('tile_x', [2, 1, 8, 2]), ('tile_r', [512, 1, 8]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,26931397
INFO:root:No: 92	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.0220491886138916, error_no=2, timestamp=1528958647.7843)	[('tile_y', [28, 4, 28, 8]), ('tile_x', [4, 8, 1, 1]), ('tile_r', [64, 16, 4]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,59636484
INFO:root:No: 93	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010885000228881836, error_no=2, timestamp=1528958647.810267)	[('tile_y', [4, 7, 16, 56]), ('tile_x', [16, 1, 1, 2]), ('tile_r', [1, 2048, 2]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,14215923
INFO:root:No: 94	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.014388084411621094, error_no=2, timestamp=1528958647.834681)	[('tile_y', [7, 1, 7, 512]), ('tile_x', [1, 1, 2, 16]), ('tile_r', [32, 2, 64]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,52850511
INFO:root:No: 95	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010967016220092773, error_no=2, timestamp=1528958647.868294)	[('tile_y', [128, 28, 1, 7]), ('tile_x', [1, 8, 4, 1]), ('tile_r', [64, 4, 16]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,39578823
INFO:root:No: 96	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010683059692382812, error_no=2, timestamp=1528958647.888925)	[('tile_y', [64, 98, 2, 2]), ('tile_x', [4, 1, 4, 2]), ('tile_r', [4, 1, 1024]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,10538369
INFO:root:No: 97	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010323047637939453, error_no=2, timestamp=1528958647.909491)	[('tile_y', [1, 3136, 4, 2]), ('tile_x', [1, 1, 1, 32]), ('tile_r', [1, 1024, 4]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,15644601
INFO:root:No: 98	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011322975158691406, error_no=2, timestamp=1528958647.931561)	[('tile_y', [1, 14, 128, 14]), ('tile_x', [4, 1, 4, 2]), ('tile_r', [2, 128, 16]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,6596871
INFO:root:No: 99	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011582136154174805, error_no=2, timestamp=1528958647.952728)	[('tile_y', [4, 2, 56, 56]), ('tile_x', [1, 8, 2, 2]), ('tile_r', [512, 4, 2]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,1913536
INFO:root:No: 100	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01055002212524414, error_no=2, timestamp=1528958647.972598)	[('tile_y', [16, 1, 49, 32]), ('tile_x', [8, 1, 4, 1]), ('tile_r', [1, 2048, 2]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,2982587
INFO:root:No: 101	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.015740156173706055, error_no=2, timestamp=1528958647.998661)	[('tile_y', [8, 14, 14, 16]), ('tile_x', [2, 8, 2, 1]), ('tile_r', [64, 4, 16]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,5934755
INFO:root:No: 102	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010483026504516602, error_no=2, timestamp=1528958648.030536)	[('tile_y', [98, 32, 8, 1]), ('tile_x', [1, 4, 1, 8]), ('tile_r', [2, 2048, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,23883309
INFO:root:No: 103	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01090097427368164, error_no=2, timestamp=1528958648.051794)	[('tile_y', [256, 1, 7, 14]), ('tile_x', [1, 8, 4, 1]), ('tile_r', [32, 64, 2]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,13583997
INFO:root:No: 104	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958658.105947)	[('tile_y', [784, 8, 4, 1]), ('tile_x', [2, 1, 8, 2]), ('tile_r', [512, 1, 8]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,38141461
INFO:root:No: 105	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010548830032348633, error_no=2, timestamp=1528958658.121204)	[('tile_y', [1, 1, 4, 6272]), ('tile_x', [1, 4, 1, 8]), ('tile_r', [512, 2, 4]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,14522195
INFO:root:No: 106	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.03671717643737793, error_no=2, timestamp=1528958658.168275)	[('tile_y', [2, 196, 64, 1]), ('tile_x', [1, 2, 1, 16]), ('tile_r', [4, 4, 256]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,54571223
INFO:root:No: 107	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.015879154205322266, error_no=2, timestamp=1528958658.221501)	[('tile_y', [16, 16, 98, 1]), ('tile_x', [2, 8, 1, 2]), ('tile_r', [1, 1024, 4]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,26787429
INFO:root:No: 108	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.014356136322021484, error_no=2, timestamp=1528958658.259818)	[('tile_y', [28, 2, 1, 448]), ('tile_x', [16, 2, 1, 1]), ('tile_r', [128, 4, 8]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,60741879
INFO:root:No: 109	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.07011198997497559, error_no=2, timestamp=1528958658.364736)	[('tile_y', [2, 1, 12544, 1]), ('tile_x', [4, 2, 2, 2]), ('tile_r', [4, 4, 256]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,65725327
INFO:root:No: 110	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.019385814666748047, error_no=2, timestamp=1528958658.434661)	[('tile_y', [128, 49, 1, 4]), ('tile_x', [1, 1, 32, 1]), ('tile_r', [4, 1024, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,23699009
INFO:root:No: 111	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.03320813179016113, error_no=2, timestamp=1528958658.491625)	[('tile_y', [4, 7, 448, 2]), ('tile_x', [1, 4, 4, 2]), ('tile_r', [2, 4, 512]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,55141376
INFO:root:No: 112	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958668.57435)	[('tile_y', [6272, 1, 4, 1]), ('tile_x', [1, 2, 2, 8]), ('tile_r', [128, 32, 1]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,45570857
INFO:root:No: 113	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010727167129516602, error_no=2, timestamp=1528958668.590269)	[('tile_y', [7, 4, 4, 224]), ('tile_x', [1, 1, 8, 4]), ('tile_r', [64, 2, 32]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,40633807
INFO:root:No: 114	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010628938674926758, error_no=2, timestamp=1528958668.611299)	[('tile_y', [2, 49, 8, 32]), ('tile_x', [1, 16, 1, 2]), ('tile_r', [64, 2, 32]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,6955768
INFO:root:No: 115	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010422945022583008, error_no=2, timestamp=1528958668.632268)	[('tile_y', [2, 1, 1792, 7]), ('tile_x', [8, 1, 4, 1]), ('tile_r', [1024, 4, 1]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,271578
INFO:root:No: 116	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010519027709960938, error_no=2, timestamp=1528958668.653465)	[('tile_y', [56, 16, 4, 7]), ('tile_x', [2, 16, 1, 1]), ('tile_r', [64, 16, 4]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,26004860
INFO:root:No: 117	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010927200317382812, error_no=2, timestamp=1528958668.675465)	[('tile_y', [4, 64, 2, 49]), ('tile_x', [4, 2, 2, 2]), ('tile_r', [2, 32, 64]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,19649824
INFO:root:No: 118	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.012124061584472656, error_no=2, timestamp=1528958668.69777)	[('tile_y', [8, 4, 28, 28]), ('tile_x', [2, 8, 1, 2]), ('tile_r', [256, 16, 1]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,34180687
INFO:root:No: 119	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.015738964080810547, error_no=2, timestamp=1528958668.722534)	[('tile_y', [32, 28, 14, 2]), ('tile_x', [8, 4, 1, 1]), ('tile_r', [1, 256, 16]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,62713645
INFO:root:No: 120	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011291027069091797, error_no=2, timestamp=1528958668.755335)	[('tile_y', [32, 2, 2, 196]), ('tile_x', [2, 4, 2, 2]), ('tile_r', [256, 16, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,56612360
INFO:root:No: 121	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011101961135864258, error_no=2, timestamp=1528958668.776287)	[('tile_y', [56, 16, 7, 4]), ('tile_x', [4, 2, 2, 2]), ('tile_r', [2, 32, 64]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,19648869
INFO:root:No: 122	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.012127161026000977, error_no=2, timestamp=1528958668.798474)	[('tile_y', [128, 7, 7, 4]), ('tile_x', [4, 2, 2, 2]), ('tile_r', [2, 4, 512]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,10285666
INFO:root:No: 123	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011286020278930664, error_no=2, timestamp=1528958668.818706)	[('tile_y', [1, 1568, 8, 2]), ('tile_x', [1, 2, 2, 8]), ('tile_r', [256, 4, 4]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,48281637
INFO:root:No: 124	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958678.873407)	[('tile_y', [256, 7, 1, 14]), ('tile_x', [2, 4, 4, 1]), ('tile_r', [512, 2, 4]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,3232952
INFO:root:No: 125	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958688.922161)	[('tile_y', [6272, 1, 2, 2]), ('tile_x', [2, 1, 8, 2]), ('tile_r', [16, 128, 2]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,36170557
INFO:root:No: 126	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.020704030990600586, error_no=2, timestamp=1528958688.947589)	[('tile_y', [64, 49, 8, 1]), ('tile_x', [4, 4, 1, 2]), ('tile_r', [128, 4, 8]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,60788310
INFO:root:No: 127	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01356816291809082, error_no=2, timestamp=1528958688.977482)	[('tile_y', [7, 7, 256, 2]), ('tile_x', [4, 1, 1, 8]), ('tile_r', [1, 128, 32]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,52584965
INFO:root:No: 128	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958699.045552)	[('tile_y', [14, 4, 448, 1]), ('tile_x', [2, 4, 2, 2]), ('tile_r', [4096, 1, 1]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,44906688
INFO:root:No: 129	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01359105110168457, error_no=2, timestamp=1528958699.064215)	[('tile_y', [1, 8, 112, 28]), ('tile_x', [2, 1, 1, 16]), ('tile_r', [64, 4, 16]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,50874309
INFO:root:No: 130	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01108407974243164, error_no=2, timestamp=1528958699.099138)	[('tile_y', [98, 2, 2, 64]), ('tile_x', [2, 16, 1, 1]), ('tile_r', [8, 8, 64]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,41775360
INFO:root:No: 131	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011016845703125, error_no=2, timestamp=1528958699.120159)	[('tile_y', [2, 1, 896, 14]), ('tile_x', [16, 2, 1, 1]), ('tile_r', [2, 256, 8]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,27846681
INFO:root:No: 132	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011159896850585938, error_no=2, timestamp=1528958699.141672)	[('tile_y', [16, 28, 2, 28]), ('tile_x', [1, 1, 16, 2]), ('tile_r', [16, 128, 2]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,13753633
INFO:root:No: 133	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958709.204358)	[('tile_y', [128, 7, 14, 2]), ('tile_x', [4, 1, 4, 2]), ('tile_r', [128, 1, 32]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,6842441
INFO:root:No: 134	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011210918426513672, error_no=2, timestamp=1528958709.220269)	[('tile_y', [49, 16, 32, 1]), ('tile_x', [4, 4, 1, 2]), ('tile_r', [16, 32, 8]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,5101980
INFO:root:No: 135	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.032584190368652344, error_no=2, timestamp=1528958709.262489)	[('tile_y', [8, 32, 7, 14]), ('tile_x', [2, 1, 4, 4]), ('tile_r', [1024, 1, 4]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,59231802
INFO:root:No: 136	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011224031448364258, error_no=2, timestamp=1528958709.310297)	[('tile_y', [448, 1, 28, 2]), ('tile_x', [8, 1, 2, 2]), ('tile_r', [4, 8, 128]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,31473669
INFO:root:No: 137	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010959863662719727, error_no=2, timestamp=1528958709.330957)	[('tile_y', [64, 56, 1, 7]), ('tile_x', [16, 1, 1, 2]), ('tile_r', [128, 4, 8]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,27151025
INFO:root:No: 138	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958719.38604)	[('tile_y', [256, 2, 1, 49]), ('tile_x', [4, 1, 2, 4]), ('tile_r', [128, 32, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,23128009
INFO:root:No: 139	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011347055435180664, error_no=2, timestamp=1528958719.402204)	[('tile_y', [16, 2, 8, 98]), ('tile_x', [8, 2, 2, 1]), ('tile_r', [8, 256, 2]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,2604432
INFO:root:No: 140	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958729.466211)	[('tile_y', [28, 14, 2, 32]), ('tile_x', [2, 1, 1, 16]), ('tile_r', [1024, 4, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,56418338
INFO:root:No: 141	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958739.51829)	[('tile_y', [98, 32, 1, 8]), ('tile_x', [2, 2, 1, 8]), ('tile_r', [1024, 2, 2]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,35462789
INFO:root:No: 142	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011144876480102539, error_no=2, timestamp=1528958739.534324)	[('tile_y', [224, 2, 8, 7]), ('tile_x', [32, 1, 1, 1]), ('tile_r', [8, 8, 64]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,52976881
INFO:root:No: 143	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011632919311523438, error_no=2, timestamp=1528958739.555827)	[('tile_y', [14, 1, 896, 2]), ('tile_x', [2, 8, 2, 1]), ('tile_r', [1, 2048, 2]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,59033184
INFO:root:No: 144	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011918067932128906, error_no=2, timestamp=1528958739.577069)	[('tile_y', [112, 8, 2, 14]), ('tile_x', [2, 2, 4, 2]), ('tile_r', [64, 64, 1]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,34442171
INFO:root:No: 145	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958749.631198)	[('tile_y', [392, 4, 2, 8]), ('tile_x', [1, 8, 1, 4]), ('tile_r', [2048, 1, 2]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,12899604
INFO:root:No: 146	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011154890060424805, error_no=2, timestamp=1528958749.646968)	[('tile_y', [1, 1568, 4, 4]), ('tile_x', [8, 1, 2, 2]), ('tile_r', [128, 32, 1]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,11885062
INFO:root:No: 147	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011336088180541992, error_no=2, timestamp=1528958749.668015)	[('tile_y', [1, 56, 224, 2]), ('tile_x', [1, 1, 4, 8]), ('tile_r', [128, 4, 8]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,38427963
INFO:root:No: 148	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.026813983917236328, error_no=2, timestamp=1528958749.705332)	[('tile_y', [4, 98, 64, 1]), ('tile_x', [2, 4, 1, 4]), ('tile_r', [8, 2, 256]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,65626222
INFO:root:No: 149	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011488914489746094, error_no=2, timestamp=1528958749.727805)	[('tile_y', [7, 4, 448, 2]), ('tile_x', [8, 1, 2, 2]), ('tile_r', [256, 8, 2]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,13240175
INFO:root:No: 150	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010370969772338867, error_no=2, timestamp=1528958749.749099)	[('tile_y', [1, 224, 112, 1]), ('tile_x', [8, 2, 2, 1]), ('tile_r', [2, 256, 8]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,16647645
INFO:root:No: 151	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010808944702148438, error_no=2, timestamp=1528958749.771415)	[('tile_y', [1, 1, 32, 784]), ('tile_x', [2, 2, 2, 4]), ('tile_r', [32, 1, 128]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,64772334
INFO:root:No: 152	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010807991027832031, error_no=2, timestamp=1528958749.793369)	[('tile_y', [2, 128, 98, 1]), ('tile_x', [1, 2, 4, 4]), ('tile_r', [8, 64, 8]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,38905032
INFO:root:No: 153	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010457992553710938, error_no=2, timestamp=1528958749.814787)	[('tile_y', [56, 1, 2, 224]), ('tile_x', [32, 1, 1, 1]), ('tile_r', [4, 512, 2]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,13923597
INFO:root:No: 154	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010755062103271484, error_no=2, timestamp=1528958749.836817)	[('tile_y', [4, 1, 49, 128]), ('tile_x', [4, 1, 8, 1]), ('tile_r', [4, 1, 1024]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,10506945
INFO:root:No: 155	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.023190975189208984, error_no=2, timestamp=1528958749.870677)	[('tile_y', [28, 32, 1, 28]), ('tile_x', [1, 8, 2, 2]), ('tile_r', [256, 16, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,56614018
INFO:root:No: 156	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011038064956665039, error_no=2, timestamp=1528958749.895509)	[('tile_y', [1, 4, 64, 98]), ('tile_x', [8, 2, 2, 1]), ('tile_r', [128, 4, 8]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,4698848
INFO:root:No: 157	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010535001754760742, error_no=2, timestamp=1528958749.915894)	[('tile_y', [1, 12544, 2, 1]), ('tile_x', [16, 2, 1, 1]), ('tile_r', [2, 2, 1024]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,44231056
INFO:root:No: 158	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010768890380859375, error_no=2, timestamp=1528958749.936997)	[('tile_y', [14, 1, 128, 14]), ('tile_x', [1, 16, 2, 1]), ('tile_r', [512, 2, 4]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,14437668
INFO:root:No: 159	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.013571023941040039, error_no=2, timestamp=1528958749.960465)	[('tile_y', [64, 1, 49, 8]), ('tile_x', [1, 4, 4, 2]), ('tile_r', [2, 512, 4]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,60316298
INFO:root:No: 160	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.03848409652709961, error_no=2, timestamp=1528958750.022329)	[('tile_y', [32, 98, 1, 8]), ('tile_x', [2, 1, 1, 16]), ('tile_r', [4, 32, 32]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,63563393
INFO:root:No: 161	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010969161987304688, error_no=2, timestamp=1528958750.063872)	[('tile_y', [98, 8, 4, 8]), ('tile_x', [1, 1, 4, 8]), ('tile_r', [1, 2, 2048]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,33500424
INFO:root:No: 162	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010745048522949219, error_no=2, timestamp=1528958750.084512)	[('tile_y', [2, 32, 7, 56]), ('tile_x', [16, 1, 1, 2]), ('tile_r', [8, 512, 1]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,34790304
INFO:root:No: 163	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01906108856201172, error_no=2, timestamp=1528958750.11362)	[('tile_y', [98, 2, 32, 4]), ('tile_x', [4, 8, 1, 1]), ('tile_r', [1, 4, 1024]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,66781733
INFO:root:No: 164	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011132001876831055, error_no=2, timestamp=1528958750.142908)	[('tile_y', [2, 14, 896, 1]), ('tile_x', [4, 1, 8, 1]), ('tile_r', [64, 2, 32]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,29354907
INFO:root:No: 165	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011892080307006836, error_no=2, timestamp=1528958750.164561)	[('tile_y', [64, 14, 14, 2]), ('tile_x', [8, 2, 2, 1]), ('tile_r', [8, 512, 1]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,34758243
INFO:root:No: 166	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.23595190048217773, error_no=2, timestamp=1528958750.409518)	[('tile_y', [2, 448, 28, 1]), ('tile_x', [1, 4, 8, 1]), ('tile_r', [4, 128, 8]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,61391172
INFO:root:No: 167	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TimeoutError(),), all_cost=10.0, error_no=6, timestamp=1528958760.487875)	[('tile_y', [7, 448, 1, 8]), ('tile_x', [4, 2, 2, 2]), ('tile_r', [2048, 2, 1]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,22605998
INFO:root:No: 168	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011166095733642578, error_no=2, timestamp=1528958760.503706)	[('tile_y', [16, 16, 7, 14]), ('tile_x', [4, 4, 2, 1]), ('tile_r', [32, 8, 16]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,6055601
INFO:root:No: 169	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011312007904052734, error_no=2, timestamp=1528958760.524745)	[('tile_y', [128, 2, 7, 14]), ('tile_x', [1, 4, 4, 2]), ('tile_r', [16, 64, 4]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,15101998
INFO:root:No: 170	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.03743100166320801, error_no=2, timestamp=1528958760.57176)	[('tile_y', [98, 8, 32, 1]), ('tile_x', [1, 1, 32, 1]), ('tile_r', [2, 256, 8]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,50309778
INFO:root:No: 171	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010478019714355469, error_no=2, timestamp=1528958760.613928)	[('tile_y', [1, 28, 128, 7]), ('tile_x', [2, 16, 1, 1]), ('tile_r', [2, 1, 2048]), ('auto_unroll_max_step', 0), ('unroll_explicit', 0)],None,6d5f33fa,10851359
INFO:root:No: 172	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.019582033157348633, error_no=2, timestamp=1528958760.643773)	[('tile_y', [28, 4, 8, 28]), ('tile_x', [2, 4, 2, 2]), ('tile_r', [4, 4, 256]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,54517462
INFO:root:No: 173	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010718822479248047, error_no=2, timestamp=1528958760.671949)	[('tile_y', [32, 98, 2, 4]), ('tile_x', [2, 1, 16, 1]), ('tile_r', [8, 64, 8]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,16425836
INFO:root:No: 174	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010719060897827148, error_no=2, timestamp=1528958760.692838)	[('tile_y', [1, 98, 8, 32]), ('tile_x', [2, 1, 2, 8]), ('tile_r', [32, 2, 64]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,41627769
INFO:root:No: 175	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.012602090835571289, error_no=2, timestamp=1528958760.715584)	[('tile_y', [1, 3136, 2, 4]), ('tile_x', [1, 2, 1, 16]), ('tile_r', [1, 512, 8]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,61717244
INFO:root:No: 176	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.11171388626098633, error_no=2, timestamp=1528958760.851703)	[('tile_y', [448, 56, 1, 1]), ('tile_x', [8, 2, 2, 1]), ('tile_r', [4, 2, 512]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,66173810
INFO:root:No: 177	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.0420839786529541, error_no=2, timestamp=1528958760.951427)	[('tile_y', [56, 2, 224, 1]), ('tile_x', [1, 8, 4, 1]), ('tile_r', [4, 32, 32]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,63479064
INFO:root:No: 178	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.12028098106384277, error_no=2, timestamp=1528958761.098738)	[('tile_y', [14, 28, 2, 32]), ('tile_x', [1, 4, 2, 4]), ('tile_r', [16, 2, 128]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,64897139
INFO:root:No: 179	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011934995651245117, error_no=2, timestamp=1528958761.159807)	[('tile_y', [98, 8, 2, 16]), ('tile_x', [8, 4, 1, 1]), ('tile_r', [16, 64, 4]), ('auto_unroll_max_step', 512), ('unroll_explicit', 0)],None,6d5f33fa,15036106
INFO:root:No: 180	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.01143503189086914, error_no=2, timestamp=1528958761.180147)	[('tile_y', [1, 7, 28, 128]), ('tile_x', [1, 2, 4, 4]), ('tile_r', [128, 8, 4]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 0)],None,6d5f33fa,25970744
INFO:root:No: 181	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.015128850936889648, error_no=2, timestamp=1528958761.204624)	[('tile_y', [1, 4, 14, 448]), ('tile_x', [1, 2, 4, 4]), ('tile_r', [2, 8, 256]), ('auto_unroll_max_step', 1500), ('unroll_explicit', 1)],None,6d5f33fa,65887704
INFO:root:No: 182	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.0107269287109375, error_no=2, timestamp=1528958761.237164)	[('tile_y', [2, 28, 56, 8]), ('tile_x', [2, 2, 1, 8]), ('tile_r', [16, 256, 1]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,34723711
INFO:root:No: 183	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.010564088821411133, error_no=2, timestamp=1528958761.257771)	[('tile_y', [7, 64, 56, 1]), ('tile_x', [4, 1, 1, 8]), ('tile_r', [16, 2, 128]), ('auto_unroll_max_step', 0), ('unroll_explicit', 1)],None,6d5f33fa,42482209
INFO:root:No: 184	GFLOPS: 0.00/0.00	result: MeasureResult(runs=(TVMError('TVMCall CFunc Error:\nTraceback (most recent call last):\n  File "/home/jian/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun\n    rv = local_pyfunc(*pyargs)\n  File "/home/jian/autotvm/python/autotvm/fleet/worker.py", line 395, in verify_pass\n    raise InstantiationError("invalid cuda kernel")\nInstantiationError: invalid cuda kernel\n',),), all_cost=0.011308908462524414, error_no=2, timestamp=1528958761.279543)	[('tile_y', [4, 8, 4, 196]), ('tile_x', [4, 2, 4, 1]), ('tile_r', [32, 8, 16]), ('auto_unroll_max_step', 512), ('unroll_explicit', 1)],None,6d5f33fa,50909969
